fix(examples/with-three-js): Upgrade drei@2.2.21 & three@0.125.0 #22365 (#22431)
If the three dependency is upgraded to version 0.125.0 and upwards, the following errors occur:
- Compilation error: Attempted import error: 'Geometry' is not exported from 'three'.
- ReferenceError: Blob is not defined.

Solution: 
Upgrade drei to `2.2.21`.